import {
  mockIp,
  mockReqId
} from '../utils/mock';

export function genCartGroupData(data) {
  const resp = {
    data: {
      isNotEmpty: true,
      storeGoods: [{
        storeId: '1000',
        storeName: '云Mall深圳旗舰店',
        storeStatus: 1,
        totalDiscountSalePrice: '9990',
        promotionGoodsList: [{
          title: null,
          promotionCode: 'EMPTY_PROMOTION',
          promotionSubCode: null,
          promotionId: null,
          tagText: null,
          promotionStatus: null,
          tag: null,
          description: null,
          doorSillRemain: null,
          isNeedAddOnShop: 0,
          goodsPromotionList: [
            // {
            //   uid: '88888888205468',
            //   saasId: '88888888',
            //   storeId: '1000',
            //   spuId: '11',
            //   skuId: '135691629',
            //   isSelected: 0,
            //   thumb: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17a.png',
            //   title: '运动连帽拉链卫衣休闲开衫长袖多色运动细绒面料运动上衣',
            //   primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-17a.png',
            //   quantity: 1,
            //   stockStatus: false,
            //   stockQuantity: 0,
            //   price: '25900',
            //   originPrice: '39900',
            //   tagPrice: null,
            //   tagText: null,
            //   roomId: null,
            //   specInfo: [{
            //       specTitle: '颜色',
            //       specValue: '军绿色',
            //     },
            //     {
            //       specTitle: '尺码',
            //       specValue: 'S',
            //     },
            //   ],
            //   joinCartTime: '2020-04-24T06:26:48.000+0000',
            //   available: 1,
            //   putOnSale: 1,
            //   etitle: null,
            // },
            // {
            //   uid: '88888888205468',
            //   saasId: '88888888',
            //   storeId: '1000',
            //   spuId: '5',
            //   skuId: '135691635',
            //   isSelected: 0,
            //   thumb: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2a.png',
            //   title: '迷你便携高颜值蓝牙无线耳机立体声只能触控式操作简约立体声耳机',
            //   primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2a.png',
            //   quantity: 1,
            //   stockStatus: true,
            //   stockQuantity: 96,
            //   price: '29000',
            //   originPrice: '29900',
            //   tagPrice: null,
            //   tagText: null,
            //   roomId: null,
            //   specInfo: [{
            //       specTitle: '颜色',
            //       specValue: '黑色',
            //     },
            //     {
            //       specTitle: '类型',
            //       specValue: '简约款',
            //     },
            //   ],
            //   joinCartTime: '2020-06-29T07:55:17.000+0000',
            //   available: 1,
            //   putOnSale: 1,
            //   etitle: null,
            // },
          ],
          lastJoinTime: null,
        }, ],
        lastJoinTime: '2020-06-29T07:55:40.000+0000',
        postageFreePromotionVo: {
          title: null,
          promotionCode: null,
          promotionSubCode: null,
          promotionId: null,
          tagText: null,
          promotionStatus: null,
          tag: null,
          description: null,
          doorSillRemain: null,
          isNeedAddOnShop: 0,
        },
      }, ],
      invalidGoodItems: [
        //   {
        //   uid: '88888888205468',
        //   saasId: '88888888',
        //   storeId: '1000',
        //   spuId: '1',
        //   skuId: '135691631',
        //   isSelected: 1,
        //   thumb: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08b.png',
        //   title: '纯色纯棉休闲圆领短袖T恤纯白亲肤厚柔软细腻面料纯白短袖套头T恤',
        //   primaryImage: 'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08b.png',
        //   quantity: 8,
        //   stockStatus: true,
        //   stockQuantity: 177,
        //   price: '26900',
        //   originPrice: '31900',
        //   tagPrice: null,
        //   tagText: null,
        //   roomId: null,
        //   specInfo: [{
        //       specTitle: '颜色',
        //       specValue: '白色',
        //     },
        //     {
        //       specTitle: '尺码',
        //       specValue: 'S',
        //     },
        //   ],
        //   joinCartTime: '2020-04-28T04:03:59.000+0000',
        //   available: 1,
        //   putOnSale: 1,
        //   etitle: null,
        // }, 
      ],
      isAllSelected: false,
      selectedGoodsCount: 16,
      totalAmount: '179997',
      totalDiscountAmount: '110000',
    },
    code: 'Success',
    msg: null,
    requestId: mockReqId(),
    clientIp: mockIp(),
    rt: 269,
    success: true,
  };

  var goodsList = [];

  for (var val in data.data) {
    var goods = data.data[val]

    goodsList.push({
      shopCartId: goods.shopCartId,
      uid: '88888888205468',
      saasId: '88888888',
      storeId: '1000',
      spuId: String(goods.item.itemId),
      itemId: String(goods.item.itemId),
      skuId: '135691622',
      isSelected: 1,
      thumb: goods.item.images[0]?.imageUrl,
      title: goods.item.title,
      primaryImage: goods.item.images[0]?.imageUrl,
      quantity: 1,
      stockStatus: true,
      stockQuantity: 3,
      price: goods.item.price * 100,
      originPrice: goods.item.price * 100,
      tagPrice: null,
      titlePrefixTags: [],
      roomId: null,
      specInfo: [],
      joinCartTime: '2020-06-29T07:55:40.000+0000',
      available: 1,
      putOnSale: 1,
      etitle: null,
    })
  }
  resp.data.storeGoods[0].promotionGoodsList[0].goodsPromotionList = goodsList
  // console.log('zdy-购物车数据解析：' + resp.data.storeGoods[0].promotionGoodsList[0].goodsPromotionList)

  return resp;
}